### ISSUE TITLE
Start using chalk for colors

### ISSUE THREAD

**Issue by Olian04** [Olian04/better-logging#13]
Chalk is an already established popular library for colorizing terminal output.
Chalk: https://github.com/chalk/chalk

Config example: 

```js
// Currently
require('better-logging')(console, {
    typeColors: Color => ({
      debug: Color.Cyan,
      log: Color.Dark_Gray,
      info: Color.White,
      warn: Color.Yellow,
      error: Color.Light_Red
    }),
    stampColor: Color => Color.Dark_Gray
});

//  Using chalk
const chalk = require('chalk');
require('better-logging')(console, {
    typeColors: {
        debug: chalk.cyan,
        info: chalk.blackBright,
        log: chalk.whiteBright,
        error: chalk.yellowBright,
        warn: chalk.blue,
    },
    stampColor: chalk.blackBright
});
```

**Comment by cdrani** [comment]
The colors in the proposed typeColors object are different from the current one for the same keys. Is this a slight mistake or new changes?

**Comment by Olian04** [comment]
@cdrani First of all, thank you for showing an interest in the development of better-logging.

I'm assuming you are referring to `Color.Dark_Gray` and `chalk.blackBright`. If you look at the color code used by better-logging and the color code used by chalk they seem to be be the same. I haven't tested to see if they actually are, I will however do so before I implement anything.

Better-logging: 
https://github.com/Olian04/better-logging/blob/247a3de02bedb86fc0db4165340410079d7e6967/src/better-logging.js#L13

ansi-styles (used by chalk):
https://github.com/chalk/ansi-styles/blob/f4df7e9fb69f14fc124cae0769fc17065c4413c5/index.js#L44

According to Wikipedia: 
>  to get red use ESC[31m, to get bright red use ESC[1;31m. /.../ Later terminals added the ability to directly specify the "bright" colors with 90-97 and 100-107.

So it looks like chalk is using the newer way of targeting colors, while better-logging currently uses the legacy way.

**Comment by Olian04** [comment]
This is now part of the 4.0 rewrite.
