### ISSUE TITLE
@types/chalk Stub types definiton

### ISSUE THREAD

**Issue by Volper212** [Olian04/better-logging#31]
The @types/chalk dependency shows warning: `npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!`

Will removing the package break anything?

**Comment by Olian04** [comment]
That package only provides type information for typescript. So if you're using javascript then you can safely remove it. However it looks like the types package isn't nessessary for chalk anymore. So I'll make sure to update the dependencies in the next release.
Thanks!

**Comment by Olian04** [comment]
This should be resolved in release 4.1.0
Thank you for submitting the issue!
