### ISSUE TITLE
[Feature Request] Preserve Line Numbers

### ISSUE THREAD

**Issue by ChuckJonas** [Olian04/better-logging#44]
**Is your feature request related to a problem? Please describe.**
Just tried this library, and it seems to be exactly what I was looking for, with one exception.  It does not preserve the line numbers which is an incredibly useful context.

Instead, everything ends up with `node_modules/better-logging/dist/lib/logger.js:43`

**Describe the solution you'd like**
<img width="878" alt="index_ts_—_pp-case-migration_and_searchControls_tsx_—_quote-tool" src="https://user-images.githubusercontent.com/5217568/94849434-a6270780-03e2-11eb-8332-2d64ff84ff83.png">

**Describe alternatives you've considered**
This is the main thing I am looking for in a log library... other features are secondary at the moment.

**Additional context**

https://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number

**Comment by Olian04** [comment]
Thank you for opening an issue!
I have a couple of question: 
1. Do you know if this problem is isolated to vscode? Could it even be isolated to only the debug console?
3. Do you know how vscode determines the line number? Is it part of the debugger? or is it using some kind of reflection that can be access during runtime?

**Comment by Olian04** [comment]
**Note to self:**
This SO answer might be useful: https://stackoverflow.com/a/32928812/6224823
However I have a feeling that the way we circumvent infinite recursion on the happy path, might collide with that SO answer.
https://github.com/Olian04/better-logging/blob/67f05f039d1e839e72640361e0d44c71a53f0f8e/src/lib/logger.ts#L9-L41

**Comment by ChuckJonas** [comment]
> Do you know if this problem is isolated to vscode? Could it even be isolated to only the debug console?

I'm not sure honestly... When using stdout, I don't think you typically get line numbers at all.

> Do you know how vscode determines the line number? Is it part of the debugger? or is it using some kind of reflection that can be access during runtime

Again, I'm not much help here... I know that you get similar behavior in chrome dev-tools, but it may be something that is implemented by the js runtime.

**Comment by Olian04** [comment]
It seems like the vscode debugger is messing with the stdout stream of the process it self. I don't think I'll be able to circumvent this unless starting a child process and proxying its stdout is on the table. Which, for better-logging, it's not.

```js
const originalStdoutWrite = process.stdout.write.bind(process.stdout);

(process.stdout as any).write = (chunk, encoding, callback) => {
  if (typeof chunk === 'string') {
    return originalStdoutWrite(`[proxy] ${chunk}`, encoding, callback);
  }

  return originalStdoutWrite(chunk, encoding, callback);
};

/*
The following lines will have the string "[proxy]" inserted before its message
however in vscode, the proxy string is omitted for some reason.
*/
console.log('foo');
console.log('bar');

process.stdout.write = originalStdoutWrite;
console.log('biz');
```
