### ISSUE TITLE
[Bug Report] saveToFile requires a path to the output file

### ISSUE THREAD

**Issue by dcoffey3296** [Olian04/better-logging#49]
**Describe the bug**
```
saveToFile: "log.txt"
```
^^ this will fail with the following error:

```
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:940:3)
    at Object.exports.decorateObject (/Users/.../node_modules/better-logging/dist/lib/decorateObject.js:16:22)
    at LoggerContext.decorate (/Users/.../node_modules/better-logging/dist/lib/logger.js:56:26)
    at Object.<anonymous> (/Users/.../log.js:3:26)
```

**To Reproduce**
set the config object with just a filename, no path:
```
saveToFile: "log.txt"
```

**Expected behavior**
no error

If a path is added to the logfile (even `"./" + logfile`), there is no error and logging is successful.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node 14.4
 - `"better-logging": "^4.4.0",`

**Additional context**
Workaround is to append a path if it doesn't exist.

**Comment by Olian04** [comment]
That's a clear oversight on my part. Thank you for bringing it to my attention.
It should be an easy fix, if you want to open a PR?
Otherwise I'll get around to it as soon as I can.

### Relevant code:

https://github.com/Olian04/better-logging/blob/d1a7c42e526199792836286d8bbf9596cee8f570/src/lib/decorateObject.ts#L15-L18

**Comment by dcoffey3296** [comment]
errr.. I failed a check.  Sorry not too familiar with typescript!  The fix worked locally in my project.

**Comment by Olian04** [comment]
> errr.. I failed a check. Sorry not too familiar with typescript! The fix worked locally in my project.

@dcoffey3296 the error is simply style error. I've opted to use single quotes for strings in this project, and you've use double quotes.
If you run `npm run lint`, then it will attempt to auto fix most style errors, and will notify you about any errors that you need to fix manually.
