### ISSUE TITLE
[Feature Request] Add function to get current Timestamp string

### ISSUE THREAD

**Issue by xetrics** [Olian04/better-logging#71]
Would be useful to be able to get the current timestamp and not log anything. Currently using process.stdout for some of my application to utilize carriage returns and it would be nice to keep my logs consistent. An example implementation could be:

`betterLogging.getTimestamp("info") // "[17:57:19] [info]"`
`betterLogging.getTimestamp(betterLogging.logTypes.INFO) // "[17:57:19] [info]"`

Alternatively, implement line updates/carriage returns to remove the need for this.

**Comment by Olian04** [comment]
While I agree that this feature sound like it's useful, I believe that it's out of scope for `better-logging`. However you could implement this feature in your project, using some of `better-logging`s internals, like this:

```js
const { betterLogging } = require('better-logging');
const { resolveConfig } = require('better-logging/dist/lib/config');

const customConfig = {}
betterLogging(console, customConfig);
const config = resolveConfig(customConfig);

const stamp = (innerContent, innerColor = config.color.base) => {
  const stamp = config.formatStamp(innerColor(innerContent))
  return config.color.base(stamp);
};

const dateStamp = () => {
  const strDate = new Date().toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: false });
  return stamp(strDate);
}

console.log('Using console.log');
process.stdout.write(`${dateStamp()} ${stamp('log', config.color.type.log)} Using stdout\n`);
```

Links to relevant internals:
* `resolveConfig`: https://github.com/Olian04/better-logging/blob/f018382f6ec2dc7d9c573f24036236f6f43d2620/src/lib/config.ts#L48-L158
* `stamp` & date formatting: https://github.com/Olian04/better-logging/blob/f018382f6ec2dc7d9c573f24036236f6f43d2620/src/lib/formatMessage.ts#L7-L22

**Comment by Olian04** [comment]
I'm closing this issue since I've determined that it's out of scope for the library. If @xetrics or anyone else believes this to be incorrect, please @ me.
