### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by eioo** [Olian04/better-logging#75]
Does this library support time zones? I didn't see anything in documentation.

I'm in Finland currently in GMT+3 time-zone, using `ts-node-dev` for developing and it shows the right time, but this library is 2 hours behind (that's 1 hour off because of day light saving)

![image](https://user-images.githubusercontent.com/26361964/205773626-267035c0-ea4c-4211-a804-ecf16402ec41.png)

I'm using Ubuntu 22.04 server currently. Love the library by the way, perfect for my needs.

**Comment by Olian04** [comment]
First of all, thank you for opening an issue!

As of [version 5.0](https://github.com/Olian04/better-logging/releases/tag/5.0.0) better-logging conforms to the [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard. With regards to the Mozilla docs implementation of the [`toISOString` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) this means that any timestamps produced by better logging will always be in UTC time and formatted like `YYYY-MM-DD` and `hh:mm:ss.mmm`.

This decision was made to make sure that timestamps produced by better-logging always are comparable between instances that might be running in different geographical regions.

Hope this helps 😄

**Comment by eioo** [comment]
I actually figured it out but forgot to close the issue, had a fresh Ubuntu install just recently and didn't set the correct time-zone. :sweat_smile: `better-logging` working as it should.

Thanks for response, I'll close this issue.
